DROP TABLE IF EXISTS TB_GERAL;

CREATE TABLE IF NOT EXISTS TB_GERAL (
	ID_TBGERAL INT NOT NULL AUTO_INCREMENT,
    UNIVERSIDADE VARCHAR(255) COLLATE LATIN1_GENERAL_CI NOT NULL,
    CURSO VARCHAR(150) COLLATE LATIN1_GENERAL_CI DEFAULT NULL,
    TURNO VARCHAR(100) COLLATE LATIN1_GENERAL_CI DEFAULT NULL,
    PRIMARY KEY (ID_TBGERAL)
)
ENGINE=MyISAM DEFAULT charset=latin1 collate=latin1_general_ci;

select * from TB_GERAL;

insert into TB_GERAL (
UNIVERSIDADE,
CURSO,
TURNO
)
VALUES
(
'UNP - UNIVERSIDADE POTIGUAR',
'SISTEMA DE INFORMAÇÃO',
'NOITE'
);
insert into TB_GERAL (
UNIVERSIDADE,
CURSO,
TURNO
)
VALUES
(
'UNP - UNIVERSIDADE POTIGUAR',
'CIÊNCIAS DA COMPUTAÇÃO',
'NOITE'
);

UPDATE TB_GERAL SET UNIVERSIDADE = 'UNP - UNIVERSIDADE POTIGUAR - ROBERTO FREIRE' WHERE ID_TBGERAL = 1;
UPDATE TB_GERAL SET UNIVERSIDADE = 'UNP - UNIVERSIDADE POTIGUAR - MOSSORÓ' WHERE ID_TBGERAL = 2;
